import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  mainSidebar: [
    {
      type: "category",
      label: "Getting Started",
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "getting-started" }],
    },
    {
      type: "category",
      label: "Code Documentation",
      collapsed: true,
      items: [
        {
          type: "category",
          label: "Backend",
          items: [{ type: "autogenerated", dirName: "backend" }],
        },
        {
          type: "category",
          label: "Frontend",
          items: [{ type: "autogenerated", dirName: "frontend" }],
        },
      ],
    },
  ],
};

export default sidebars;
