import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  mainSidebar: [
    'introduction',
    'installation',
    'configuration',
    'operation',
    'cli',
    'webserver',
    'architecture',
    'community',
    'testing',
    'troubleshooting',
    {
      type: 'category',
      label: 'Code Documentation',
      items: [{ type: 'autogenerated', dirName: 'auto-docs' }],
    },
  ],
};

export default sidebars;
