import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  mainSidebar: [
    'introduction',
    'installation',
    'configuration',
    'operation',
    'cli',
    'webserver',
    'architecture',
    'community',
    'testing',
    'troubleshooting',
    {
      type: 'category',
      label: 'Code Documentation',
      items: [
        {
          type: 'category',
          label: 'Backend',
          items: [{ type: 'autogenerated', dirName: 'backend' }],
        },
        {
          type: 'category',
          label: 'Frontend',
          items: [{ type: 'autogenerated', dirName: 'frontend' }],
        },
      ],
    },
  ],
};

export default sidebars;
